[package]
name = "puncture-client-db"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
diesel = { workspace = true }
diesel_migrations = { workspace = true }
serde = { workspace = true } 